spring:
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 25052743368-bnsp3cset51jquuvt91fqogdj9naa948.apps.googleusercontent.com
          clientSecret: oufa6QqbqBLrzk8ul6MyPanH